### ISSUE TITLE
Add UUIDs in all necessary places in the data registry

### ISSUE THREAD

**Issue by alysbrett** [ScottishCovidResponse/data-registry#20]

**Comment by alahiff** [comment]
The following models will need UUID fields added:
* Issue
* Object
* CodeRun
* Author

We should also add a uniqueness constraint to `FileType` so that it doesn't need a UUID and to ensure we don't have multiple versions of the same file type.

**Comment by richardreeve** [comment]
We also need an organisation table to give RORs to organisations (@agbeltran, is this right?) to add the schema that will also have a UUID (because some orgs will not have RORs, like authors and ORCIDs), and a many-to-many link that connects authors to organisations.

**Comment by agbeltran** [comment]
yes, for organisations we can consider the Research Organisation Registry or [ROR](https://ror.org/); there are others such as the Global Research Identifier Database or [GRID](https://www.grid.ac/), and for funders the CrossRef Funders Registry [FundRef](https://www.crossref.org/services/funder-registry/), and there are also mappings between them

**Comment by richardreeve** [comment]
Is there some reason to prefer ROR over GRID or vice-versa, or should the organisation table include both? If we wanted to include funders (and we might), that sounds like yet another table?

**Comment by alahiff** [comment]
UUIDs have been added to `CodeRun` and `Object` (https://github.com/ScottishCovidResponse/data-registry/commit/d2367cb0772c8887814de51bd8d405bdd3e7825c#diff-98f4560b884627ff362583b7ebe2d14b6696968274da8098aa26993eae760f01), with field name `unique_id`. By default UUIDs are generated automatically, but it is possible to provide one of course (needed when syncing registries). If you specify something which  is not in the form of a standard UUID you will get an error, and if you specify a UUID which has already been used you will get an error.

`FileType` now has a uniqueness constraint (https://github.com/ScottishCovidResponse/data-registry/commit/1068349b2a3a64d8cc4c6db874c2115b3bcf83a1#diff-98f4560b884627ff362583b7ebe2d14b6696968274da8098aa26993eae760f01).

**Comment by agbeltran** [comment]
A minor comment, but wouldn't it be better to call the field ```uuid``` to reflect how it is generated and used? The ```uuid``` serves is an internal unique identifier, while the previously existing```id``` field in many cases will cover a globally unique and also external point for interoperability, even if not always.

**Comment by agbeltran** [comment]
> Is there some reason to prefer ROR over GRID or vice-versa, or should the organisation table include both? If we wanted to include funders (and we might), that sounds like yet another table?

The selection between ROR vs GRID, which in any case have mappings between them, is around their governance and our interest in interoperability. GRID is maintained by the Digital Science company, while ROR is a wider consortium (see [governance and steering group](https://ror.org/governance/)), which includes Digital Science, DataCite and others. I suggest we use ROR by default. 

It seems to me that we will need an organisation table, and this will cover funders (which is an organisation role).

**Comment by richardreeve** [comment]
Okay, then @alahiff shall we add an `Organisation` table with an optional ROR and a uuid field? Also, the `Author` table needs an optional ORCID field and the ability to connect authors to (possibly multiple) orgs.

**Comment by alahiff** [comment]
@agbeltran I almost called it `uuid` but then changed my mind. I've now changed `unique_id` to `uuid`, as that makes it clearer.

It's the other way around - `id` is an internal unique identifier (i.e. only within the context of a single database) whilst `uuid` is globally unique.

**Comment by alahiff** [comment]
@richardreeve Instead of adding authors directly to objects we will need to be able to add (author, organisation) to objects instead. To do this I think we will also need an `AuthorOrganisation` table to construct the pairs of authors and organisations, with (`author`, `organisation`) having a uniqueness constraint.

(Just adding an organisation foreign key to the authors table won't work of course since authors may have written papers whilst working at different organisations).

**Comment by richardreeve** [comment]
Ah, I see what you mean @alahiff - well spotted. The problem with that may be (I presume?) that in most situations we probably won't know author organisations - for anything that comes from a paper for instance? @agbeltran do you know what information we can extract from a DOI? I tried to find something about this, but I couldn't find the right site - I think you said there was an API you could use.

On the other hand, if author and organisation are optional (but you have to have at least one) in the `AuthorOrganisation` table, then that would allow us to reference institutions (ONS, say) as an author as well as individuals, which would be a big plus.

**Comment by richardreeve** [comment]
Oh, do we also need to worry about authors with multiple affiliations?

**Comment by alahiff** [comment]
Probably we do...

**Comment by alahiff** [comment]
And do we need to maintain the correct order of authors?

**Comment by alahiff** [comment]
I've added an `Organisation` model to my test instance. For example, to add an organisation you would POST json like the following to /api/organisation/:
```
{
    "name": "United Kingdom Atomic Energy Authority",
    "ror_id": "0361bwx64"
}
```
Listing organisations gives back items like this:
```
{
    "url": "http://localhost:8000/api/organisation/1/",
    "last_updated": "2021-05-13T12:28:32.058056Z",
    "name": "United Kingdom Atomic Energy Authority",
    "ror_id": "0361bwx64",
    "uuid": "ed3c7a50-1bbb-4c60-ad1e-6d4a130370a6",
    "updated_by": "http://localhost:8000/api/users/1/",
    "ror_url": "https://ror.org/0361bwx64"
}
```
Only the 9-character string part of the ROR ID is stored in the database but the model has a method to return the actual URL.

I guess to be really clever we could have a validation function to check that the provided ROR IDs are actually real, but I haven't done that yet.

**Comment by alahiff** [comment]
I have a working version of a method that allows authors and organisations to be added to an `Object`. There is a `ObjectAuthorOrg` model (I couldn't think of a better name!) where you specify an object, an author, a list of organisations and a priority (used for ordering authors). For example:
```
{
    "url": "http://localhost:8000/api/object_author_org/1/",
    "last_updated": "2021-05-13T13:24:34.926218Z",
    "priority": 1,
    "updated_by": "http://localhost:8000/api/users/1/",
    "object": "http://localhost:8000/api/object/1/",
    "author": "http://localhost:8000/api/author/1/",
    "organisations": [
        "http://localhost:8000/api/organisation/1/"
    ]
}
```
As before, objects have a list of authors, but now they are `ObjectAuthorOrg`s rather than `Author`s:
```
{
    "url": "http://localhost:8000/api/object/1/",
    "last_updated": "2021-05-13T13:23:23.923503Z",
    "description": "This is a test",
    "uuid": "ee9680fa-5a60-4df1-b958-a35a3574eb53",
    "updated_by": "http://localhost:8000/api/users/1/",
    "storage_location": null,
    "file_type": null,
    "issues": [],
    "components": [],
    "data_product": null,
    "code_repo_release": null,
    "external_object": null,
    "quality_control": null,
    "authors": [
        "http://localhost:8000/api/object_author_org/1/"
    ],
    "licences": [],
    "keywords": []
}
```
I'm not sure if anyone can think of a better way of doing this?

**Comment by richardreeve** [comment]
I guess we do need to care about author order, because ultimately we want to be able to mint our own DOIs and we don't just want to do that with the authors in a random order... ? I guess we'll be assuming that that as you add an ObjectAuthorOrg to then table the number will increment for every new Author (or Org without an Author, though not the same Author with a different Org)?

As far as validating is concerned, that would be good at some point, but so would some way of searching for orgs and authors on ROR or ORCID - as with so many other things, it would be good to understand what APIs ORCID / ROR / whoever expose to query their databases... this is all a separate issue though I think...

**Comment by agbeltran** [comment]
> It's the other way around - `id` is an internal unique identifier (i.e. only within the context of a single database) whilst `uuid` is globally unique.

@alahiff ok, but then with field will hold the external globally unique identifiers for the entities (such as ORCID for Author, ROR for Organisation, DOI for Data Product, etc)? If ```uuid```, then we need another field name

**Comment by agbeltran** [comment]
> Ah, I see what you mean @alahiff - well spotted. The problem with that may be (I presume?) that in most situations we probably won't know author organisations - for anything that comes from a paper for instance? @agbeltran do you know what information we can extract from a DOI? I tried to find something about this, but I couldn't find the right site - I think you said there was an API you could use.

The DataCite API: https://support.datacite.org/docs/api

**Comment by alahiff** [comment]
@agbeltran We just have additional fields for those, e.g. to add an author you would post:
```
{
    "family_name": "Einsten",
    "personal_name": "Albert",
    "orcid": "0000-0003-2125-060X"
}
```
or for an organisation:
```
{
    "name": "UK Research and Innovation",
    "ror": "001aqnf71"
}
```

**Comment by alahiff** [comment]
For RORs it's easy to query the API to check things, e.g. https://api.ror.org/organizations/05ch0aw77

Looking at orcid.org it appears as though they only provide authenticated API access (see e.g. https://info.orcid.org/documentation/features/public-api/#easy-faq-2606) so it's not quite so easy.

**Comment by alahiff** [comment]
I realised I don't think we need to have the `priority` field at all - as long as the `ObjectAuthorOrg` are created in the correct order for a particular paper, we just need to retrieve the list of `ObjectAuthorOrg`s ordered by ascending id (integers) in order to retain the correct ordering of authors.

**Comment by alahiff** [comment]
At the bottom of https://scottishcovidresponse.github.io/docs/data_pipeline/interface/ is this text:

_When the session is initialised a “run id” is created to uniquely identify that code run. It is constructed by forming the SHA1 hash of the configuration file content, plus the date time string_

Maybe we should store this in the `CodeRun` instead of using a random UUID?

**Comment by richardreeve** [comment]
I'm pretty easy about this. Whatever you think is best. I don't know whether that's a good way of generating a UUID or not tbh?

**Comment by alahiff** [comment]
Doing something like this is probably simpler (in Python):
```
from uuid import uuid4
uuid = uuid4()
```
If necessary other languages have a similar function. This is then consistent with the other UUIDs.

**Comment by richardreeve** [comment]
@alahiff @nathan-cummings-ukaea - is this complete now?

**Comment by alahiff** [comment]
I think this is complete now, so closing.
