### ISSUE TITLE
Update static schema

### ISSUE THREAD

**Issue by bobturneruk** [ScottishCovidResponse/data-registry#30]
Please add links to static schema and source.

**Comment by bobturneruk** [comment]
I think this is the "static" schema https://data.scrc.uk/static/images/schema.svg

**Comment by soniamitchell** [comment]
The link is available via the drop down menus in https://data.scrc.uk/ 

Note that it doesn't update automatically whenever the registry is changed.

**Comment by richardreeve** [comment]
I think @alahiff can do this once we've finished messing with it - i.e. once #20 is done - or maybe it's easy to do now just to stay up to date?

**Comment by alahiff** [comment]
I haven't actually applied any new changes to the registry yet.

I've added an `update.sh` script to the registry which does schema updates (`manage.py makemigrations` followed by `manage.py migrate`) then updates the schema png and svg. So as long as we use this script rather than just manually running `makemigrations` and `migrate` the schema will be kept up to date with the database.

**Comment by richardreeve** [comment]
I'm wondering whether it would make sense to put this in the wiki (that you need to run the `update.sh` script) @alahiff as I can't see it in the installation guide, and I'm not sure where else it would be?
